using X39.Util;
using Xunit;

namespace X39.Roslyn.OpenTelemetry.Tests;

public class SpecializedAttributesTests : CompilationTestBaseClass
{
    private const string ArgActivityCode = """
                                           using System.Diagnostics;
                                           using X39.Roslyn.OpenTelemetry.Attributes;
                                           namespace TestNamespace;

                                           public partial class {0}ActivityTest
                                           {{
                                               [{0}Activity(CreateActivitySource = true)]
                                               private static partial Activity? StartMyActivity();
                                           }}
                                           """;

    private const string ArgActivityExpected = """
                                               // <auto-generated/>
                                               #nullable enable
                                               using System.Diagnostics;
                                               using System.ComponentModel;
                                               using System.Collections.Generic;

                                               namespace TestNamespace;
                                               partial class {0}ActivityTest
                                               {{
                                                   private static ActivitySource MyActivitySource = new("My");
                                                   private static partial Activity? StartMyActivity()
                                                   {{
                                                       return MyActivitySource.StartActivity(
                                                           "My",
                                                           ActivityKind.{0}
                                                       );
                                                   }}
                                               }}

                                               """;


    // @formatter:max_line_length 5000
    [Theory]
    [InlineData("Client")]
    [InlineData("Consumer")]
    [InlineData("Internal")]
    [InlineData("Producer")]
    [InlineData("Server")]
    // @formatter:max_line_length restore
    public void ActivityKindGetsRecognized(string activityKind)
    {
        var generatedFiles = AssertCompilationAndGetGeneratedFiles(ArgActivityCode.Format(activityKind), []);

        // Complex generators should be tested using text comparison.
        var (_, classOutput) = Assert.Single(
            generatedFiles,
            f => f.FilePath.EndsWith(string.Concat(activityKind, "ActivityTest", ".", "My", ".g.cs"))
        );
        Assert.Equal(ArgActivityExpected.Format(activityKind), classOutput, ignoreLineEndingDifferences: true);
    }
}