//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X39.Roslyn.OpenTelemetry.Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("X39.Roslyn.OpenTelemetry.Generator.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source generator could not resolve the `ActivitySource` for the method.
        ///The reason for this could be that:
        ///- The method is static and the `ActivitySource` present in the class is not static.
        ///  In this case, adjust the modifier of either the method or the `ActivitySource` to be similar.
        ///- There is no `ActivitySource` present in the class and neither the method, the class nor
        ///  the assembly are decorated with the `ActivitySourceReferenceAttribute`.
        ///  In this case, add the `ActivitySourceReferenceAtt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Diagnostics_ActivitySourceCouldNotBeResolved_Description {
            get {
                return ResourceManager.GetString("Diagnostics_ActivitySourceCouldNotBeResolved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve `ActivitySource` for method &apos;{0}&apos;.
        /// </summary>
        internal static string Diagnostics_ActivitySourceCouldNotBeResolved_MessageFormat {
            get {
                return ResourceManager.GetString("Diagnostics_ActivitySourceCouldNotBeResolved_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve `ActivitySource` for method.
        /// </summary>
        internal static string Diagnostics_ActivitySourceCouldNotBeResolved_Title {
            get {
                return ResourceManager.GetString("Diagnostics_ActivitySourceCouldNotBeResolved_Title", resourceCulture);
            }
        }
    }
}
